### ISSUE TITLE
Rechtsbetrekking "recht om verzoek aanpassing arbeidsduur bij eigen werkgever in te dienen"

### ISSUE THREAD

**Issue by diederikd** [diederikd/DeBrug#14]
Moet er voor deze rechtsbetrekking in het subjectieve recht een rechtsbetrekking zijn per arbeidsovereenkomst?

Dan is de rechtsbetrekking ook bepalend voor welke arbeidsovereenkomst je een verzoek indient.

**Comment by sjirnijssen** [comment]
Hoi Diederik,

Helemaal mee eens. In de wet staat arbeidsovereenkomst.

Hoe ging het vorige week met de presentatie?

Zie hieronder in line.

Groet

Sjir Nijssen

PNA Group

Tel:     +31 (0)88-777 0 444
Mob: +31 (0)6-21 510 844
Fax:    +31 (0)88-777 0 499
E-mail: sjir.nijssen@pna-group.com<mailto:sjir.nijssen@pna-group.com>
-------------------------------------------------------
http://www.pna-group.com<http://www.pna-group.com/>

Van: DD [mailto:notifications@github.com]
Verzonden: zondag 12 maart 2017 11:55
Aan: diederikd/DeBrug <DeBrug@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [diederikd/DeBrug] Rechtsbetrekking "recht om verzoek aanpassing arbeidsduur bij eigen werkgever in te dienen" (#14)


Moet er voor deze rechtsbetrekking in het subjectieve recht een rechtsbetrekking zijn per arbeidsovereenkomst?  [[Sjir: m.i. wel.]]

Dan is de rechtsbetrekking ook bepalend voor welke arbeidsovereenkomst je een verzoek indient. [[Sjir: mee eens.]]
