### ISSUE TITLE
datum van afwijzing of inwilliging

### ISSUE THREAD

**Issue by diederikd** [diederikd/DeBrug#16]
Bij het nalopen van je laatste Waa model in pdf zag ik dat we informatie missen om de laatste voorwaarde van 2.3 te kunnen evalueren.
 
Voorstel is om twee extra velden op te nemen bij Werknemer, te weten
Meest recente datum van afwijzing of inwilliging
Aanduiding afwijzing of inwilliging.

**Comment by sjirnijssen** [comment]
Prima
